version: 2.1
jobs:
  build:
    docker:
      - image: yakworks/builder:bash-make
    steps:
      - checkout
      - run: make test
      # test some other stuff
      - run: make config-bot-git-user
      # if it meets the criteria to be IS_RELEASABLE, this will bump version and tag release
      - run: make VERBOSE=1 semantic-release

workflows:
  build-flow:
    jobs:
      - build:
          context: bot-context # context with shared ENV vars
