version: 2.1
jobs:
  build:
    docker:
      - image: yakworks/bullseye:core
    steps:
      - checkout
      - run: apt-get update
      # - run: make install-shellcheck-alpine
      - run: apt-get update
      - run: make debian.install-circle-deps
      - run: make check
      # test some other stuff
      - run: make vault.decrypt
      - run: make git.config-bot-user
      # if it meets the criteria to be IS_RELEASABLE, this will bump version and tag release on github
      - run: make ship.version

workflows:
  build-flow:
    jobs:
      - build:
          context: bot-context # context with shared ENV vars
